[qt5-feedback-haptics-droid-vibrator] Add support for new Android vibrator API.
mer-hybris/qt5-feedback-haptics-droid-vibrator pull request #5
Opened 2017-07-13 17:40 UTC by mlehtima

Needed for Android 7 based ports.

2017-07-13 17:57 UTC, jusa commented
:+1:

2017-07-13 17:58 UTC, jusa approved these changes

2017-07-14 09:45 UTC, jusa requested changes

2017-07-14 09:45 UTC, jusa commented on qfeedback.cpp
> +    , dev(NULL)
enclose with ifdefs

2017-07-14 10:01 UTC, mkosola approved these changes

2017-07-14 10:03 UTC, merged